# Generated by Django 5.1.3 on 2025-04-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0003_paymentrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='sender',
            new_name='requester',
        ),
        migrations.RemoveField(
            model_name='paymentrequest',
            name='created_at',
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='currency',
            field=models.CharField(choices=[('GBP', 'Pounds (£)'), ('USD', 'Dollars ($)'), ('EUR', 'Euros (€)')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='message',
            field=models.TextField(),
        ),
    ]
