# Generated by Django 5.1.3 on 2025-04-15 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0004_rename_sender_payment_requester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payapp.paymentrequest'),
        ),
    ]
