# Generated by Django 5.1.3 on 2025-04-15 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0005_notification_related_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='requester',
            new_name='sender',
        ),
    ]
