# Generated by Django 5.1.3 on 2025-04-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0006_rename_requester_payment_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='cleared',
            field=models.BooleanField(default=False),
        ),
    ]
